name: logger
description: Small, easy to use and extensible logger which prints beautiful logs.
version: 1.0.0
homepage: https://sarbagyastha.com.np

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  io: ^0.3.4

dev_dependencies:
  test: any
  pedantic: ^1.9.0
